### ISSUE TITLE
Ċ token appears randomly in the dataset

### ISSUE THREAD

**Issue by appleternity** [HITSZ-HLT/AEG#1]
Thanks for sharing the dataset and the code. I am just curious about why there are "Ċ" tokens randomly appeared in the dataset? And is it okay to just remove it though (`text = text.replace("Ċ", "")`)?

Thanks.

**Comment by benjpau** [comment]
Thank you for your interest in our paper, and sorry for the late reply.
The Ċ token actually indicates a line break, i.e. the end of a paragraph. We use this symbol instead of "\n" for easier saving and processing.
